---
title: "Power in Data Feminism"
author: "Madison Williams"
theme: journal
---

Data can help us observe power dynamics in society. As data feminists it is our responsibility to observe power dynamics and help protect minoritized groups. The authors of the book Data Feminism believe that more intersectional data helps us do good data science. Most projects whether for funding or policy need data to help support their claims. Systems of power often replicate themselves in our society and most data scientists are members of the dominant social group. Data scientists decide what data is valuable and can help start a conversation. A lack of diversity in data science has been shown in the data we have available to us. The United States is desperately lacking in maternal data and this partly because men lead the conversation on what is valuable in data science. 

We talked last class about the personal dilemma we may feel by accepting high paying data science jobs with values which may not align with the tenants of data feminism. During class someone commented on the fact that if we do not take these jobs they will continue to be filled by the dominant members of society. This is true but the power chapter takes this a step further. When data scientists have homogeneous backgrounds we miss things. Data is not counted, mistakes are overlooked, and bias continues to be coded into our work. Perhaps you are continuing to participate in the structural domain of oppression but you may be able to provide a new perspective. Not everyone has the privilege to think about this ethical dilemma. Many people have student loan debt, family’s to support, or bills to pay and are not able to say no to high paying jobs at large corporations. I think it is our responsibility to use data science to help make the world more equitable. These discussions have left me thinking a lot about how we can make a difference in the spaces which we occupy. 

References: 
Catherine D'Ignazio and Lauren Klein.Data Feminism, The Power Chapter.(2020). Retrieved from
https://data-feminism.mitpress.mit.edu/dash/pub/vi8obxh7/overview
