---
title: "Resume"
author: Madison Williams 
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
---

<!-- Contact Me! {#contact} -->
<!-- ================================================================================ -->

#### <i class="fa fa-envelope"></i> williams.madison101@gmail.com

#### <i class="fa fa-github"></i> [github.com/mawilliams99](https://github.com/mawilliams99)

**I like to apply to work opportunities which speak to my passions, the environment and social justice. I am incredibly grateful for the experiences I have had and I'm excited for the future.**

Education {data-icon=graduation-cap data-concise=true}
================================================================================

### Smith College

B.A. in Statistical Data Sciences and a minor in Environmental Science & Policy

Class of 2021 

Northampton, Massachusetts. United States


Professional Experience: {data-icon=laptop}
================================================================================


#### *Lab Intern*, ForestGEO Ecosystems and Climate Lab  Institute for Global Environmental Strategies (IGES)

June 2021 - Current 

- Investigate and review hundreds of scientific studies included in the ForestGEO ForC database
- Used Excel, GitHub, and RStudio to revise incomplete data and create additional data
- Attended ForestGeo seminars and weekly lab meetings 
- Produced a research report and presentation of my work

--------------------------------------------------------------------------------

#### *Lab Intern*, ForestGEO Ecosystems and Climate Lab  Institute for Global Environmental Strategies (IGES)

June 2021 - Current 

- Investigate and review hundreds of scientific studies included in the ForestGEO ForC database
- Used Excel, GitHub, and RStudio to revise incomplete data and create additional data
- Attended ForestGeo seminars and weekly lab meetings 
- Produced a research report and presentation of my work

Skills {#skills}
--------------------------------------------------------------------------------

- Proficient in Python, DataWrapper, Java, and Rstudio (GGPlot, Shiny, RandomForest)

- Expericence with Microsoft Office

- Professionally trained in [liberating structures](https://www.liberatingstructures.com), alternative way to approach and design how people work together

Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.

